"use client"

import type React from "react"
import { useState } from "react"
import { MenuOnlyItemCard } from "./MenuOnlyItemCard"
import { MenuFilters } from "../../delivery/components/MenuFilters"
import type { Category, MenuItem } from "../../delivery/types"

const categorySeeds = [
  { id: "all", name: "Tous", icon: "🍽️" },
  { id: "popular", name: "Populaire", icon: "🔥" },
  { id: "shawarma", name: "Shawarma", icon: "🌯" },
  { id: "manakish", name: "Manakish", icon: "🥖" },
  { id: "pizza", name: "Pizzas", icon: "🍕" },
  { id: "burger", name: "Burgers", icon: "🍔" },
  { id: "hot-dishes", name: "Plats chauds", icon: "🍲" },
  { id: "mezze", name: "Mezzés", icon: "🥙" },
  { id: "dessert", name: "Desserts", icon: "🍰" },
  { id: "drink", name: "Boissons", icon: "🍵" },
]

const categories: Category[] = categorySeeds.map((c, i) => ({
  id: c.id,
  name: c.name,
  description: "",
  displayOrder: i,
  isActive: true,
}))

const menuItems = [
  // SHAWARMA
  {
    id: 1,
    name: "Shawarma Poulet",
    description: "Poulet mariné aux épices, sauce tahina, légumes frais",
    price: 8.99,
    imageUrl: "/syrian-chicken-shawarma-wrap.jpg",
    category: "shawarma",
    rating: 4.9,
    reviews: 245,
    prepTime: "10-15 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 12,
    calories: 450,
    dietaryInfo: [],
  },
  {
    id: 2,
    name: "Shawarma Viande",
    description: "Viande d'agneau marinée, sauce à l'ail, pickles",
    price: 9.99,
    imageUrl: "/syrian-beef-shawarma-platter.jpg",
    category: "shawarma",
    rating: 4.8,
    reviews: 198,
    prepTime: "10-15 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 12,
    calories: 520,
    dietaryInfo: [],
  },
  {
    id: 3,
    name: "Shawarma Mixte",
    description: "Poulet et viande d'agneau, double sauce",
    price: 10.99,
    imageUrl: "/mixed-shawarma-syrian-style.jpg",
    category: "shawarma",
    rating: 4.9,
    reviews: 167,
    prepTime: "12-17 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "sesame"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 14,
    calories: 580,
    dietaryInfo: [],
  },

  // MANAKISH
  {
    id: 4,
    name: "Manakish Zaatar",
    description: "Pain libanais au zaatar et huile d'olive",
    price: 4.99,
    imageUrl: "/manakish-zaatar-lebanese-flatbread.jpg",
    category: "manakish",
    rating: 4.7,
    reviews: 312,
    prepTime: "8-12 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 10,
    calories: 280,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 5,
    name: "Manakish Fromage",
    description: "Pain garni de fromage akkawi fondu",
    price: 5.99,
    imageUrl: "/manakish-cheese-akkawi-flatbread.jpg",
    category: "manakish",
    rating: 4.6,
    reviews: 256,
    prepTime: "8-12 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 10,
    calories: 320,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 6,
    name: "Manakish Mixte",
    description: "Zaatar et fromage sur pain chaud",
    price: 6.49,
    imageUrl: "/manakish-mixed-zaatar-cheese.jpg",
    category: "manakish",
    rating: 4.8,
    reviews: 189,
    prepTime: "8-12 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose", "sesame"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 10,
    calories: 350,
    dietaryInfo: ["Végétarien"],
  },

  // PLATS CHAUDS SYRIENS
  {
    id: 7,
    name: "Kibbeh",
    description: "Boulettes de viande et boulgour farcies, servies avec yaourt",
    price: 12.99,
    imageUrl: "/syrian-kibbeh-meatballs-bulgur.jpg",
    category: "hot-dishes",
    rating: 4.9,
    reviews: 234,
    prepTime: "15-20 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 18,
    calories: 480,
    dietaryInfo: [],
  },
  {
    id: 8,
    name: "Kebab Halabi",
    description: "Brochettes d'agneau aux épices d'Alep, riz et salade",
    price: 14.99,
    imageUrl: "/kebab-halabi-aleppo-style-lamb.jpg",
    category: "hot-dishes",
    rating: 4.9,
    reviews: 287,
    prepTime: "18-25 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 22,
    calories: 620,
    dietaryInfo: [],
  },
  {
    id: 9,
    name: "Riz à la Syrienne",
    description: "Riz basmati aux vermicelles, pignons de pin et amandes",
    price: 7.99,
    imageUrl: "/syrian-rice-vermicelli-nuts.jpg",
    category: "hot-dishes",
    rating: 4.6,
    reviews: 145,
    prepTime: "12-15 min",
    isPopular: false,
    isNew: false,
    allergens: ["nuts"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 13,
    calories: 380,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 10,
    name: "Shish Taouk",
    description: "Brochettes de poulet mariné au citron et à l'ail",
    price: 11.99,
    imageUrl: "/shish-taouk-chicken-skewers-lebanese-grilled-garli.jpg",
    category: "hot-dishes",
    rating: 4.8,
    reviews: 198,
    prepTime: "15-20 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 17,
    calories: 420,
    dietaryInfo: [],
  },
  {
    id: 11,
    name: "Makloubeh",
    description: "Riz renversé aux légumes et viande, yaourt",
    price: 13.99,
    imageUrl: "/maqluba-makloubeh-upside-down-rice-meat-vegetables.jpg",
    category: "hot-dishes",
    rating: 4.7,
    reviews: 167,
    prepTime: "20-25 min",
    isPopular: false,
    isNew: true,
    allergens: ["lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 22,
    calories: 550,
    dietaryInfo: [],
  },
  {
    id: 12,
    name: "Fattet Djej",
    description: "Poulet sur lit de pain grillé, riz, sauce yaourt et pignons",
    price: 12.99,
    imageUrl: "/fatteh-chicken-yogurt-pine-nuts-bread-rice-lebanes.jpg",
    category: "hot-dishes",
    rating: 4.8,
    reviews: 178,
    prepTime: "18-23 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose", "nuts"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 20,
    calories: 580,
    dietaryInfo: [],
  },

  // MEZZÉS
  {
    id: 13,
    name: "Houmous",
    description: "Purée de pois chiches, tahina, huile d'olive",
    price: 5.99,
    imageUrl: "/hummus-chickpea-tahini-dip.jpg",
    category: "mezze",
    rating: 4.9,
    reviews: 412,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: ["sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 14,
    name: "Moutabbal",
    description: "Caviar d'aubergines grillées, tahina, ail",
    price: 6.49,
    imageUrl: "/moutabal-baba-ganoush-eggplant.jpg",
    category: "mezze",
    rating: 4.8,
    reviews: 345,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: ["sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 160,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 15,
    name: "Taboulé",
    description: "Persil frais, tomates, boulgour, citron, menthe",
    price: 5.49,
    imageUrl: "/tabbouleh-parsley-salad-bulgur.jpg",
    category: "mezze",
    rating: 4.7,
    reviews: 289,
    prepTime: "5 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 120,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 16,
    name: "Falafel",
    description: "Beignets de pois chiches et fèves aux épices (6 pièces)",
    price: 6.99,
    imageUrl: "/falafel-chickpea-fritters-middle-eastern-fried-gol.jpg",
    category: "mezze",
    rating: 4.8,
    reviews: 356,
    prepTime: "8-12 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 10,
    calories: 280,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 17,
    name: "Feuilles de Vigne",
    description: "Feuilles farcies au riz, tomates, épices",
    price: 6.0,
    category: "mezze",
    imageUrl: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
    rating: 4.5,
    reviews: 71,
    prepTime: 5,
    isPopular: false,
    allergens: ["Gluten"],
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 18,
    name: "Kebbé Nayé",
    description: "Tartare de viande crue, boulgour, épices",
    price: 13.0,
    category: "mezze",
    imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop",
    rating: 4.9,
    reviews: 67,
    prepTime: 8,
    isPopular: false,
    isNew: true,
    allergens: ["Gluten"],
  },
  {
    id: 19,
    name: "Labneh",
    description: "Yaourt égoutté, huile d'olive, zaatar",
    price: 5.0,
    imageUrl: "/labneh-yogurt-cheese-olive-oil-zaatar-middle-easte.jpg",
    category: "mezze",
    rating: 4.6,
    reviews: 89,
    prepTime: 3,
    isPopular: false,
    allergens: ["Lactose"],
    isVegetarian: true,
  },

  // DESSERTS ORIENTAUX
  {
    id: 20,
    name: "Kunafa",
    description: "Pâtisserie au fromage, sirop de fleur d'oranger",
    price: 7.5,
    imageUrl: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400&h=300&fit=crop",
    category: "dessert",
    rating: 4.8,
    reviews: 156,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: ["Gluten", "Lactose"],
    isVegetarian: true,
  },
  {
    id: 21,
    name: "Maamoul",
    description: "Biscuits fourrés aux dattes et pistaches",
    price: 5.5,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop",
    category: "dessert",
    rating: 4.7,
    reviews: 94,
    prepTime: "3 min",
    isPopular: false,
    isNew: false,
    allergens: ["Gluten", "Noix"],
    isVegetarian: true,
  },
  {
    id: 22,
    name: "Baklawa",
    description: "Pâtisserie feuilletée aux pistaches et miel (4 pièces)",
    price: 6.99,
    imageUrl: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&h=300&fit=crop",
    category: "dessert",
    rating: 4.9,
    reviews: 456,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "nuts"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 280,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 23,
    name: "Maamoul",
    description: "Petits gâteaux fourrés aux dattes et noix (6 pièces)",
    price: 7.49,
    imageUrl: "/maamoul-cookies-dates-pistachios-arabic-pastry-semolina.jpg",
    category: "dessert",
    rating: 4.8,
    reviews: 312,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "nuts"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 320,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 24,
    name: "Knafeh",
    description: "Cheveux d'ange au fromage fondu et sirop de rose",
    price: 8.99,
    imageUrl: "/knafeh-kunafa-cheese-dessert-syrup-shredded-phyllo.jpg",
    category: "dessert",
    rating: 4.9,
    reviews: 389,
    prepTime: "8-10 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 9,
    calories: 420,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 25,
    name: "Halawet el Jibn",
    description: "Rouleaux de fromage doux farcis à la crème",
    price: 7.99,
    imageUrl: "/halawet-el-jibn-cheese-rolls-cream-pistachios-syri.jpg",
    category: "dessert",
    rating: 4.7,
    reviews: 234,
    prepTime: "5 min",
    isPopular: false,
    isNew: true,
    allergens: ["lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 360,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 26,
    name: "Qatayef",
    description: "Crêpes farcies aux noix et fromage, sirop de fleur d'oranger",
    price: 6.99,
    imageUrl: "/qatayef-arabic-pancakes-stuffed-nuts-cheese-syrup.jpg",
    category: "dessert",
    rating: 4.8,
    reviews: 267,
    prepTime: "5 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose", "nuts"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 340,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 27,
    name: "Riz au Lait",
    description: "Crème de riz, eau de rose, pistaches",
    price: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    category: "dessert",
    rating: 4.6,
    reviews: 78,
    prepTime: "5 min",
    isPopular: false,
    isNew: false,
    allergens: ["Lactose", "Noix"],
    isVegetarian: true,
  },

  // BOISSONS ORIENTALES
  {
    id: 28,
    name: "Thé à la Menthe",
    description: "Thé vert infusé aux feuilles de menthe fraîche",
    price: 2.99,
    imageUrl: "/mint-tea-fresh-leaves-arabic-middle-eastern-hot-be.jpg",
    category: "drink",
    rating: 4.7,
    reviews: 523,
    prepTime: "3 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 3,
    calories: 20,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 29,
    name: "Café Turc",
    description: "Café traditionnel finement moulu, servi avec cardamome",
    price: 3.49,
    imageUrl: "/turkish-coffee-cardamom-traditional-cup-foam.jpg",
    category: "drink",
    rating: 4.8,
    reviews: 412,
    prepTime: "5 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 5,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 30,
    name: "Limonade Syrienne",
    description: "Citron frais, eau de fleur d'oranger, menthe",
    price: 3.99,
    imageUrl: "/syrian-lemonade-lemon-orange-blossom-water-mint-dr.jpg",
    category: "drink",
    rating: 4.6,
    reviews: 298,
    prepTime: "3 min",
    isPopular: false,
    isNew: false,
    allergens: [],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 3,
    calories: 80,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 31,
    name: "Jallab",
    description: "Sirop de dattes et raisins, pignons de pin, raisins secs",
    price: 4.49,
    imageUrl: "/halawet-el-jibn-cheese-rolls-cream-pistachios-syri.jpg",
    category: "drink",
    rating: 4.7,
    reviews: 234,
    prepTime: "3 min",
    isPopular: false,
    isNew: true,
    allergens: ["nuts"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 3,
    calories: 150,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 32,
    name: "Ayran",
    description: "Boisson rafraîchissante au yaourt salé",
    price: 2.99,
    imageUrl: "/ayran-yogurt-drink-mint-salty-middle-eastern-bever.jpg",
    category: "drink",
    rating: 4.5,
    reviews: 187,
    prepTime: "2 min",
    isPopular: false,
    isNew: false,
    allergens: ["lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 2,
    calories: 60,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 33,
    name: "Qamar al-Din",
    description: "Jus d'abricot traditionnel syrien",
    price: 3.99,
    imageUrl: "/qamar-al-din-apricot-juice-syrian-drink-traditiona.jpg",
    category: "drink",
    rating: 4.8,
    reviews: 267,
    prepTime: "2 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 2,
    calories: 120,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 34,
    name: "Pizza Margherita",
    description: "Tomate, mozzarella, basilic frais",
    price: 12.99,
    imageUrl: "/pizza-margherita-basil-mozzarella-tomato.jpg",
    category: "pizza",
    rating: 4.8,
    reviews: 124,
    prepTime: "15-20 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 17,
    calories: 650,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 35,
    name: "Pizza 4 Fromages",
    description: "Mozzarella, gorgonzola, chèvre, parmesan",
    price: 14.99,
    imageUrl: "/four-cheese-pizza-quattro-formaggi-gorgonzola.jpg",
    category: "pizza",
    rating: 4.7,
    reviews: 98,
    prepTime: "15-20 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 17,
    calories: 720,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 36,
    name: "Pizza Regina",
    description: "Tomate, mozzarella, jambon, champignons",
    price: 13.99,
    imageUrl: "/pizza-regina-ham-mushrooms-cheese.jpg",
    category: "pizza",
    rating: 4.6,
    reviews: 87,
    prepTime: "15-20 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 17,
    calories: 680,
    dietaryInfo: [],
  },
  {
    id: 37,
    name: "Pizza Végétarienne",
    description: "Tomate, mozzarella, légumes grillés, olives",
    price: 13.49,
    imageUrl: "/vegetarian-pizza-grilled-vegetables-olives.jpg",
    category: "pizza",
    rating: 4.7,
    reviews: 76,
    prepTime: "15-20 min",
    isPopular: false,
    isNew: true,
    allergens: ["gluten", "lactose"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 17,
    calories: 590,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 38,
    name: "Pizza Orientale",
    description: "Viande hachée, poivrons, oignons, épices syriennes",
    price: 15.99,
    imageUrl: "/middle-eastern-pizza-spiced-meat-peppers.jpg",
    category: "pizza",
    rating: 4.9,
    reviews: 145,
    prepTime: "18-22 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "lactose"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 20,
    calories: 750,
    dietaryInfo: [],
  },

  // BURGERS
  {
    id: 39,
    name: "Burger Classic",
    description: "Bœuf angus, cheddar, sauce maison",
    price: 10.5,
    imageUrl: "/classic-beef-burger-cheddar-cheese-lettuce.jpg",
    category: "burger",
    rating: 4.7,
    reviews: 88,
    prepTime: "10-15 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "lactose", "eggs"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 13,
    calories: 680,
    dietaryInfo: [],
  },
  {
    id: 40,
    name: "Burger Poulet Crispy",
    description: "Poulet pané croustillant, salade, sauce curry",
    price: 9.99,
    imageUrl: "/crispy-chicken-burger-breaded-curry-sauce.jpg",
    category: "burger",
    rating: 4.6,
    reviews: 102,
    prepTime: "12-16 min",
    isPopular: false,
    isNew: false,
    allergens: ["gluten", "eggs"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 14,
    calories: 620,
    dietaryInfo: [],
  },
  {
    id: 41,
    name: "Burger Végétarien",
    description: "Steak de légumes, avocat, tomate",
    price: 9.5,
    imageUrl: "/vegetarian-veggie-burger-avocado-tomato.jpg",
    category: "burger",
    rating: 4.5,
    reviews: 67,
    prepTime: "10-14 min",
    isPopular: false,
    isNew: true,
    allergens: ["gluten"],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 12,
    calories: 520,
    dietaryInfo: ["Végétarien"],
  },
  {
    id: 42,
    name: "Burger Syrien",
    description: "Viande épicée, houmous, pickles, tahini",
    price: 11.99,
    imageUrl: "/middle-eastern-burger-hummus-tahini-spiced-meat.jpg",
    category: "burger",
    rating: 4.9,
    reviews: 156,
    prepTime: "12-16 min",
    isPopular: true,
    isNew: false,
    allergens: ["gluten", "sesame"],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 14,
    calories: 650,
    dietaryInfo: [],
  },

  // PLUS DE BOISSONS
  {
    id: 43,
    name: "Coca-Cola",
    description: "Boisson gazeuse rafraîchissante 33cl",
    price: 2.5,
    imageUrl: "/coca-cola-glass-bottle-ice-cold.jpg",
    category: "drink",
    rating: 4.5,
    reviews: 234,
    prepTime: "1 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 1,
    calories: 140,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 44,
    name: "Fanta Orange",
    description: "Boisson gazeuse à l'orange 33cl",
    price: 2.5,
    imageUrl: "/fanta-orange-soda-bottle-refreshing.jpg",
    category: "drink",
    rating: 4.4,
    reviews: 187,
    prepTime: "1 min",
    isPopular: false,
    isNew: false,
    allergens: [],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 1,
    calories: 150,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 45,
    name: "Eau Minérale",
    description: "Eau minérale naturelle 50cl",
    price: 1.5,
    imageUrl: "/mineral-water-bottle-natural-fresh.jpg",
    category: "drink",
    rating: 4.8,
    reviews: 312,
    prepTime: "1 min",
    isPopular: false,
    isNew: false,
    allergens: [],
    isFeatured: false,
    isAvailable: true,
    preparationTime: 1,
    calories: 0,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
  {
    id: 46,
    name: "Jus d'Orange Frais",
    description: "Oranges pressées à la minute",
    price: 4.5,
    imageUrl: "/fresh-orange-juice-glass-pressed-citrus.jpg",
    category: "drink",
    rating: 4.9,
    reviews: 267,
    prepTime: "3-5 min",
    isPopular: true,
    isNew: false,
    allergens: [],
    isFeatured: true,
    isAvailable: true,
    preparationTime: 4,
    calories: 110,
    dietaryInfo: ["Végétarien", "Vegan"],
  },
]

type RawMenuRow = (typeof menuItems)[number]

function toMenuItem(it: RawMenuRow): MenuItem {
  return {
    id: String(it.id),
    name: it.name,
    description: it.description,
    price: it.price,
    imageUrl: it.imageUrl,
    categoryId: it.category,
    categoryName: it.category,
    preparationTime: it.preparationTime ?? 0,
    calories: it.calories,
    allergens: it.allergens,
    dietaryInfo: it.dietaryInfo,
    isAvailable: it.isAvailable ?? true,
    isFeatured: it.isFeatured ?? false,
  }
}

const menuData: MenuItem[] = menuItems.map(toMenuItem)

interface MenuOnlyGridProps {
  restaurantId: string
}

export const MenuOnlyGrid: React.FC<MenuOnlyGridProps> = () => {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState("")
  const [dietaryFilters, setDietaryFilters] = useState<string[]>([])
  const [priceRange, setPriceRange] = useState<[number, number]>([0, 100])

  const filteredItems = menuData.filter((item) => {
    const matchesCategory =
      !selectedCategory ||
      selectedCategory === "all" ||
      (selectedCategory === "popular" ? item.isFeatured : item.categoryId === selectedCategory)
    const matchesSearch =
      item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.description.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesDietaryFilters =
      dietaryFilters.length === 0 ||
      dietaryFilters.every((filter) => (item.allergens ?? []).includes(filter))
    const matchesPriceRange = item.price >= priceRange[0] && item.price <= priceRange[1]
    return matchesCategory && matchesSearch && matchesDietaryFilters && matchesPriceRange
  })

  return (
    <div className="space-y-10">
      <div className="text-center max-w-2xl mx-auto space-y-5">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#d4af37]/10 border border-[#d4af37]/20 text-[#6b5a47] text-sm font-medium">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
            />
          </svg>
          <span>Saveurs Authentiques</span>
        </div>
        <h1 className="text-5xl font-light text-[#6b5a47] tracking-tight">
          Notre <span className="font-semibold text-[#8b7355]">Menu</span>
        </h1>
        <p className="text-base text-[#9c8b7a] leading-relaxed">
          Découvrez nos plats délicieux, préparés avec des ingrédients frais et des recettes traditionnelles syriennes
        </p>
      </div>

      {/* Filters */}
      <MenuFilters
        categories={categories}
        selectedCategory={selectedCategory}
        onCategoryChange={setSelectedCategory}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        dietaryFilters={dietaryFilters}
        onDietaryFiltersChange={setDietaryFilters}
        priceRange={priceRange}
        onPriceRangeChange={setPriceRange}
      />

      {/* Menu Grid */}
      {filteredItems.length === 0 ? (
        <div className="text-center py-20">
          <div className="w-20 h-20 mx-auto mb-5 rounded-full bg-[#d4af37]/10 flex items-center justify-center">
            <svg className="w-10 h-10 text-[#d4af37]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
          <p className="text-xl text-[#6b5a47] font-medium mb-2">Aucun plat trouvé</p>
          <p className="text-[#9c8b7a]">Essayez d'ajuster vos filtres de recherche</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredItems.map((item) => (
            <MenuOnlyItemCard key={item.id} item={item} />
          ))}
        </div>
      )}
    </div>
  )
}
